kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username: kevinbacon
      password: pa55word
      repo: nemo83/simple-play-app
      tags: latest
