kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: mozilla/sbt
    commands:
      - sbt stage
  - name: docker
    image: plugins/docker
    environment:
      DOCKER_HUB_TOKEN:
        from_secret: DOCKER_HUB_TOKEN
    settings:
      repo: nemo83/simple-play-app
      tags: latest
      auth: DOCKER_HUB_TOKEN
