kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: mozilla/sbt
    commands:
      - env
      - sbt stage
  - name: docker
    image: plugins/docker
    settings:
      repo: nemo83/simple-play-app
      tags: latest
      username:
        from_secret: DOCKER_HUB_USERNAME
      password:
        from_secret: DOCKER_HUB_TOKEN
