kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: mozilla/sbt
    commands:
      - sbt stage
  - name: docker
    image: plugins/docker
    settings:
      repo: nemo83/simple-play-app
      tags: latest
      token:
        from_secret: DOCKER_HUB_TOKEN
